import unittest

from domain.factory.pull_request_factory import GitHubPullRequestFactory
from domain.github import GithubClient

from infrastructure.pull_request_repository import PullRequestRepository


class TestOrganizationService(unittest.TestCase):

    def setUp(self):
        self.pull_request_repo = PullRequestRepository()

    def test_github_pull_request_parser(self):
        pull_request_webhooh_payload = {
            "action": "closed",
            "number": 4,
            "pull_request": {
                "url": "https://api.github.com/repos/Codertocat/Hello-World/pulls/2",
                "id": 279147437,
                "node_id": "MDExOlB1bGxSZXF1ZXN0Mjc5MTQ3NDM3",
                "html_url": "https://github.com/Codertocat/Hello-World/pull/2",
                "diff_url": "https://github.com/Codertocat/Hello-World/pull/2.diff",
                "patch_url": "https://github.com/Codertocat/Hello-World/pull/2.patch",
                "issue_url": "https://api.github.com/repos/Codertocat/Hello-World/issues/2",
                "number": 2,
                "state": "open",
                "locked": False,
                "title": "Update the README with new information.",
                "user": {
                    "login": "Codertocat",
                    "id": 21031067,
                    "node_id": "MDQ6VXNlcjIxMDMxMDY3",
                    "avatar_url": "https://avatars1.githubusercontent.com/u/21031067?v=4",
                    "gravatar_id": "",
                    "url": "https://api.github.com/users/Codertocat",
                    "html_url": "https://github.com/Codertocat",
                    "followers_url": "https://api.github.com/users/Codertocat/followers",
                    "following_url": "https://api.github.com/users/Codertocat/following{/other_user}",
                    "gists_url": "https://api.github.com/users/Codertocat/gists{/gist_id}",
                    "starred_url": "https://api.github.com/users/Codertocat/starred{/owner}{/repo}",
                    "subscriptions_url": "https://api.github.com/users/Codertocat/subscriptions",
                    "organizations_url": "https://api.github.com/users/Codertocat/orgs",
                    "repos_url": "https://api.github.com/users/Codertocat/repos",
                    "events_url": "https://api.github.com/users/Codertocat/events{/privacy}",
                    "received_events_url": "https://api.github.com/users/Codertocat/received_events",
                    "type": "User",
                    "site_admin": False
                },
                "body": "This is a pretty simple change that we need to pull into master.",
                "created_at": "2019-05-15T15:20:33Z",
                "updated_at": "2019-05-15T15:20:33Z",
                "closed_at": None,
                "merged_at": None,
                "merge_commit_sha": None,
                "assignee": None,
                "assignees": [

                ],
                "requested_reviewers": [

                ],
                "requested_teams": [

                ],
                "labels": [

                ],
                "milestone": None,
                "commits_url": "https://api.github.com/repos/Codertocat/Hello-World/pulls/2/commits",
                "review_comments_url": "https://api.github.com/repos/Codertocat/Hello-World/pulls/2/comments",
                "review_comment_url": "https://api.github.com/repos/Codertocat/Hello-World/pulls/comments{/number}",
                "comments_url": "https://api.github.com/repos/Codertocat/Hello-World/issues/2/comments",
                "statuses_url": "https://api.github.com/repos/Codertocat/Hello-World/statuses/ec26c3e57ca3a959ca5aad62de7213c562f8c821",
                "head": {
                    "label": "Codertocat:changes",
                    "ref": "changes",
                    "sha": "ec26c3e57ca3a959ca5aad62de7213c562f8c821",
                    "user": {
                        "login": "Codertocat",
                        "id": 21031067,
                        "node_id": "MDQ6VXNlcjIxMDMxMDY3",
                        "avatar_url": "https://avatars1.githubusercontent.com/u/21031067?v=4",
                        "gravatar_id": "",
                        "url": "https://api.github.com/users/Codertocat",
                        "html_url": "https://github.com/Codertocat",
                        "followers_url": "https://api.github.com/users/Codertocat/followers",
                        "following_url": "https://api.github.com/users/Codertocat/following{/other_user}",
                        "gists_url": "https://api.github.com/users/Codertocat/gists{/gist_id}",
                        "starred_url": "https://api.github.com/users/Codertocat/starred{/owner}{/repo}",
                        "subscriptions_url": "https://api.github.com/users/Codertocat/subscriptions",
                        "organizations_url": "https://api.github.com/users/Codertocat/orgs",
                        "repos_url": "https://api.github.com/users/Codertocat/repos",
                        "events_url": "https://api.github.com/users/Codertocat/events{/privacy}",
                        "received_events_url": "https://api.github.com/users/Codertocat/received_events",
                        "type": "User",
                        "site_admin": False
                    },
                    "repo": {
                        "id": 186853002,
                        "node_id": "MDEwOlJlcG9zaXRvcnkxODY4NTMwMDI=",
                        "name": "Hello-World",
                        "full_name": "Codertocat/Hello-World",
                        "private": False,
                        "owner": {
                            "login": "Codertocat",
                            "id": 1031067,
                            "node_id": "MDQ6VXNlcjIxMDMxMDY3",
                            "avatar_url": "https://avatars1.githubusercontent.com/u/21031067?v=4",
                            "gravatar_id": "",
                            "url": "https://api.github.com/users/Codertocat",
                            "html_url": "https://github.com/Codertocat",
                            "followers_url": "https://api.github.com/users/Codertocat/followers",
                            "following_url": "https://api.github.com/users/Codertocat/following{/other_user}",
                            "gists_url": "https://api.github.com/users/Codertocat/gists{/gist_id}",
                            "starred_url": "https://api.github.com/users/Codertocat/starred{/owner}{/repo}",
                            "subscriptions_url": "https://api.github.com/users/Codertocat/subscriptions",
                            "organizations_url": "https://api.github.com/users/Codertocat/orgs",
                            "repos_url": "https://api.github.com/users/Codertocat/repos",
                            "events_url": "https://api.github.com/users/Codertocat/events{/privacy}",
                            "received_events_url": "https://api.github.com/users/Codertocat/received_events",
                            "type": "User",
                            "site_admin": False
                        },
                        "html_url": "https://github.com/Codertocat/Hello-World",
                        "description": None,
                        "fork": False,
                        "url": "https://api.github.com/repos/Codertocat/Hello-World",
                        "forks_url": "https://api.github.com/repos/Codertocat/Hello-World/forks",
                        "keys_url": "https://api.github.com/repos/Codertocat/Hello-World/keys{/key_id}",
                        "collaborators_url": "https://api.github.com/repos/Codertocat/Hello-World/collaborators{/collaborator}",
                        "teams_url": "https://api.github.com/repos/Codertocat/Hello-World/teams",
                        "hooks_url": "https://api.github.com/repos/Codertocat/Hello-World/hooks",
                        "issue_events_url": "https://api.github.com/repos/Codertocat/Hello-World/issues/events{/number}",
                        "events_url": "https://api.github.com/repos/Codertocat/Hello-World/events",
                        "assignees_url": "https://api.github.com/repos/Codertocat/Hello-World/assignees{/user}",
                        "branches_url": "https://api.github.com/repos/Codertocat/Hello-World/branches{/branch}",
                        "tags_url": "https://api.github.com/repos/Codertocat/Hello-World/tags",
                        "blobs_url": "https://api.github.com/repos/Codertocat/Hello-World/git/blobs{/sha}",
                        "git_tags_url": "https://api.github.com/repos/Codertocat/Hello-World/git/tags{/sha}",
                        "git_refs_url": "https://api.github.com/repos/Codertocat/Hello-World/git/refs{/sha}",
                        "trees_url": "https://api.github.com/repos/Codertocat/Hello-World/git/trees{/sha}",
                        "statuses_url": "https://api.github.com/repos/Codertocat/Hello-World/statuses/{sha}",
                        "languages_url": "https://api.github.com/repos/Codertocat/Hello-World/languages",
                        "stargazers_url": "https://api.github.com/repos/Codertocat/Hello-World/stargazers",
                        "contributors_url": "https://api.github.com/repos/Codertocat/Hello-World/contributors",
                        "subscribers_url": "https://api.github.com/repos/Codertocat/Hello-World/subscribers",
                        "subscription_url": "https://api.github.com/repos/Codertocat/Hello-World/subscription",
                        "commits_url": "https://api.github.com/repos/Codertocat/Hello-World/commits{/sha}",
                        "git_commits_url": "https://api.github.com/repos/Codertocat/Hello-World/git/commits{/sha}",
                        "comments_url": "https://api.github.com/repos/Codertocat/Hello-World/comments{/number}",
                        "issue_comment_url": "https://api.github.com/repos/Codertocat/Hello-World/issues/comments{/number}",
                        "contents_url": "https://api.github.com/repos/Codertocat/Hello-World/contents/{+path}",
                        "compare_url": "https://api.github.com/repos/Codertocat/Hello-World/compare/{base}...{head}",
                        "merges_url": "https://api.github.com/repos/Codertocat/Hello-World/merges",
                        "archive_url": "https://api.github.com/repos/Codertocat/Hello-World/{archive_format}{/ref}",
                        "downloads_url": "https://api.github.com/repos/Codertocat/Hello-World/downloads",
                        "issues_url": "https://api.github.com/repos/Codertocat/Hello-World/issues{/number}",
                        "pulls_url": "https://api.github.com/repos/Codertocat/Hello-World/pulls{/number}",
                        "milestones_url": "https://api.github.com/repos/Codertocat/Hello-World/milestones{/number}",
                        "notifications_url": "https://api.github.com/repos/Codertocat/Hello-World/notifications{?since,all,participating}",
                        "labels_url": "https://api.github.com/repos/Codertocat/Hello-World/labels{/name}",
                        "releases_url": "https://api.github.com/repos/Codertocat/Hello-World/releases{/id}",
                        "deployments_url": "https://api.github.com/repos/Codertocat/Hello-World/deployments",
                        "created_at": "2019-05-15T15:19:25Z",
                        "updated_at": "2019-05-15T15:19:27Z",
                        "pushed_at": "2019-05-15T15:20:32Z",
                        "git_url": "git://github.com/Codertocat/Hello-World.git",
                        "ssh_url": "git@github.com:Codertocat/Hello-World.git",
                        "clone_url": "https://github.com/Codertocat/Hello-World.git",
                        "svn_url": "https://github.com/Codertocat/Hello-World",
                        "homepage": None,
                        "size": 0,
                        "stargazers_count": 0,
                        "watchers_count": 0,
                        "language": None,
                        "has_issues": True,
                        "has_projects": True,
                        "has_downloads": True,
                        "has_wiki": True,
                        "has_pages": True,
                        "forks_count": 0,
                        "mirror_url": None,
                        "archived": False,
                        "disabled": False,
                        "open_issues_count": 2,
                        "license": None,
                        "forks": 0,
                        "open_issues": 2,
                        "watchers": 0,
                        "default_branch": "master"
                    }
                },
                "base": {
                    "label": "Codertocat:master",
                    "ref": "master",
                    "sha": "f95f852bd8fca8fcc58a9a2d6c842781e32a215e",
                    "user": {
                        "login": "Codertocat",
                        "id": 21031067,
                        "node_id": "MDQ6VXNlcjIxMDMxMDY3",
                        "avatar_url": "https://avatars1.githubusercontent.com/u/21031067?v=4",
                        "gravatar_id": "",
                        "url": "https://api.github.com/users/Codertocat",
                        "html_url": "https://github.com/Codertocat",
                        "followers_url": "https://api.github.com/users/Codertocat/followers",
                        "following_url": "https://api.github.com/users/Codertocat/following{/other_user}",
                        "gists_url": "https://api.github.com/users/Codertocat/gists{/gist_id}",
                        "starred_url": "https://api.github.com/users/Codertocat/starred{/owner}{/repo}",
                        "subscriptions_url": "https://api.github.com/users/Codertocat/subscriptions",
                        "organizations_url": "https://api.github.com/users/Codertocat/orgs",
                        "repos_url": "https://api.github.com/users/Codertocat/repos",
                        "events_url": "https://api.github.com/users/Codertocat/events{/privacy}",
                        "received_events_url": "https://api.github.com/users/Codertocat/received_events",
                        "type": "User",
                        "site_admin": False
                    },
                    "repo": {
                        "id": 186853002,
                        "node_id": "MDEwOlJlcG9zaXRvcnkxODY4NTMwMDI=",
                        "name": "Hello-World",
                        "full_name": "Codertocat/Hello-World",
                        "private": False,
                        "owner": {
                            "login": "Codertocat",
                            "id": 21031067,
                            "node_id": "MDQ6VXNlcjIxMDMxMDY3",
                            "avatar_url": "https://avatars1.githubusercontent.com/u/21031067?v=4",
                            "gravatar_id": "",
                            "url": "https://api.github.com/users/Codertocat",
                            "html_url": "https://github.com/Codertocat",
                            "followers_url": "https://api.github.com/users/Codertocat/followers",
                            "following_url": "https://api.github.com/users/Codertocat/following{/other_user}",
                            "gists_url": "https://api.github.com/users/Codertocat/gists{/gist_id}",
                            "starred_url": "https://api.github.com/users/Codertocat/starred{/owner}{/repo}",
                            "subscriptions_url": "https://api.github.com/users/Codertocat/subscriptions",
                            "organizations_url": "https://api.github.com/users/Codertocat/orgs",
                            "repos_url": "https://api.github.com/users/Codertocat/repos",
                            "events_url": "https://api.github.com/users/Codertocat/events{/privacy}",
                            "received_events_url": "https://api.github.com/users/Codertocat/received_events",
                            "type": "User",
                            "site_admin": False
                        },
                        "html_url": "https://github.com/Codertocat/Hello-World",
                        "description": None,
                        "fork": False,
                        "url": "https://api.github.com/repos/Codertocat/Hello-World",
                        "forks_url": "https://api.github.com/repos/Codertocat/Hello-World/forks",
                        "keys_url": "https://api.github.com/repos/Codertocat/Hello-World/keys{/key_id}",
                        "collaborators_url": "https://api.github.com/repos/Codertocat/Hello-World/collaborators{/collaborator}",
                        "teams_url": "https://api.github.com/repos/Codertocat/Hello-World/teams",
                        "hooks_url": "https://api.github.com/repos/Codertocat/Hello-World/hooks",
                        "issue_events_url": "https://api.github.com/repos/Codertocat/Hello-World/issues/events{/number}",
                        "events_url": "https://api.github.com/repos/Codertocat/Hello-World/events",
                        "assignees_url": "https://api.github.com/repos/Codertocat/Hello-World/assignees{/user}",
                        "branches_url": "https://api.github.com/repos/Codertocat/Hello-World/branches{/branch}",
                        "tags_url": "https://api.github.com/repos/Codertocat/Hello-World/tags",
                        "blobs_url": "https://api.github.com/repos/Codertocat/Hello-World/git/blobs{/sha}",
                        "git_tags_url": "https://api.github.com/repos/Codertocat/Hello-World/git/tags{/sha}",
                        "git_refs_url": "https://api.github.com/repos/Codertocat/Hello-World/git/refs{/sha}",
                        "trees_url": "https://api.github.com/repos/Codertocat/Hello-World/git/trees{/sha}",
                        "statuses_url": "https://api.github.com/repos/Codertocat/Hello-World/statuses/{sha}",
                        "languages_url": "https://api.github.com/repos/Codertocat/Hello-World/languages",
                        "stargazers_url": "https://api.github.com/repos/Codertocat/Hello-World/stargazers",
                        "contributors_url": "https://api.github.com/repos/Codertocat/Hello-World/contributors",
                        "subscribers_url": "https://api.github.com/repos/Codertocat/Hello-World/subscribers",
                        "subscription_url": "https://api.github.com/repos/Codertocat/Hello-World/subscription",
                        "commits_url": "https://api.github.com/repos/Codertocat/Hello-World/commits{/sha}",
                        "git_commits_url": "https://api.github.com/repos/Codertocat/Hello-World/git/commits{/sha}",
                        "comments_url": "https://api.github.com/repos/Codertocat/Hello-World/comments{/number}",
                        "issue_comment_url": "https://api.github.com/repos/Codertocat/Hello-World/issues/comments{/number}",
                        "contents_url": "https://api.github.com/repos/Codertocat/Hello-World/contents/{+path}",
                        "compare_url": "https://api.github.com/repos/Codertocat/Hello-World/compare/{base}...{head}",
                        "merges_url": "https://api.github.com/repos/Codertocat/Hello-World/merges",
                        "archive_url": "https://api.github.com/repos/Codertocat/Hello-World/{archive_format}{/ref}",
                        "downloads_url": "https://api.github.com/repos/Codertocat/Hello-World/downloads",
                        "issues_url": "https://api.github.com/repos/Codertocat/Hello-World/issues{/number}",
                        "pulls_url": "https://api.github.com/repos/Codertocat/Hello-World/pulls{/number}",
                        "milestones_url": "https://api.github.com/repos/Codertocat/Hello-World/milestones{/number}",
                        "notifications_url": "https://api.github.com/repos/Codertocat/Hello-World/notifications{?since,all,participating}",
                        "labels_url": "https://api.github.com/repos/Codertocat/Hello-World/labels{/name}",
                        "releases_url": "https://api.github.com/repos/Codertocat/Hello-World/releases{/id}",
                        "deployments_url": "https://api.github.com/repos/Codertocat/Hello-World/deployments",
                        "created_at": "2019-05-15T15:19:25Z",
                        "updated_at": "2019-05-15T15:19:27Z",
                        "pushed_at": "2019-05-15T15:20:32Z",
                        "git_url": "git://github.com/Codertocat/Hello-World.git",
                        "ssh_url": "git@github.com:Codertocat/Hello-World.git",
                        "clone_url": "https://github.com/Codertocat/Hello-World.git",
                        "svn_url": "https://github.com/Codertocat/Hello-World",
                        "homepage": None,
                        "size": 0,
                        "stargazers_count": 0,
                        "watchers_count": 0,
                        "language": None,
                        "has_issues": True,
                        "has_projects": True,
                        "has_downloads": True,
                        "has_wiki": True,
                        "has_pages": True,
                        "forks_count": 0,
                        "mirror_url": None,
                        "archived": False,
                        "disabled": False,
                        "open_issues_count": 2,
                        "license": None,
                        "forks": 0,
                        "open_issues": 2,
                        "watchers": 0,
                        "default_branch": "master"
                    }
                },
                "_links": {
                    "self": {
                        "href": "https://api.github.com/repos/Codertocat/Hello-World/pulls/2"
                    },
                    "html": {
                        "href": "https://github.com/Codertocat/Hello-World/pull/2"
                    },
                    "issue": {
                        "href": "https://api.github.com/repos/Codertocat/Hello-World/issues/2"
                    },
                    "comments": {
                        "href": "https://api.github.com/repos/Codertocat/Hello-World/issues/2/comments"
                    },
                    "review_comments": {
                        "href": "https://api.github.com/repos/Codertocat/Hello-World/pulls/2/comments"
                    },
                    "review_comment": {
                        "href": "https://api.github.com/repos/Codertocat/Hello-World/pulls/comments{/number}"
                    },
                    "commits": {
                        "href": "https://api.github.com/repos/Codertocat/Hello-World/pulls/2/commits"
                    },
                    "statuses": {
                        "href": "https://api.github.com/repos/Codertocat/Hello-World/statuses/ec26c3e57ca3a959ca5aad62de7213c562f8c821"
                    }
                },
                "author_association": "OWNER",
                "draft": False,
                "merged": True,
                "mergeable": None,
                "rebaseable": None,
                "mergeable_state": "unknown",
                "merged_by": None,
                "comments": 0,
                "review_comments": 0,
                "maintainer_can_modify": False,
                "commits": 1,
                "additions": 1,
                "deletions": 1,
                "changed_files": 1
            },
            "repository": {
                "id": 186853002,
                "node_id": "MDEwOlJlcG9zaXRvcnkxODY4NTMwMDI=",
                "name": "Hello-World",
                "full_name": "Codertocat/Hello-World",
                "private": False,
                "owner": {
                    "login": "Codertocat",
                    "id": 21031067,
                    "node_id": "MDQ6VXNlcjIxMDMxMDY3",
                    "avatar_url": "https://avatars1.githubusercontent.com/u/21031067?v=4",
                    "gravatar_id": "",
                    "url": "https://api.github.com/users/Codertocat",
                    "html_url": "https://github.com/Codertocat",
                    "followers_url": "https://api.github.com/users/Codertocat/followers",
                    "following_url": "https://api.github.com/users/Codertocat/following{/other_user}",
                    "gists_url": "https://api.github.com/users/Codertocat/gists{/gist_id}",
                    "starred_url": "https://api.github.com/users/Codertocat/starred{/owner}{/repo}",
                    "subscriptions_url": "https://api.github.com/users/Codertocat/subscriptions",
                    "organizations_url": "https://api.github.com/users/Codertocat/orgs",
                    "repos_url": "https://api.github.com/users/Codertocat/repos",
                    "events_url": "https://api.github.com/users/Codertocat/events{/privacy}",
                    "received_events_url": "https://api.github.com/users/Codertocat/received_events",
                    "type": "User",
                    "site_admin": False
                },
                "html_url": "https://github.com/Codertocat/Hello-World21",
                "description": None,
                "fork": False,
                "url": "https://api.github.com/repos/Codertocat/Hello-World",
                "forks_url": "https://api.github.com/repos/Codertocat/Hello-World/forks",
                "keys_url": "https://api.github.com/repos/Codertocat/Hello-World/keys{/key_id}",
                "collaborators_url": "https://api.github.com/repos/Codertocat/Hello-World/collaborators{/collaborator}",
                "teams_url": "https://api.github.com/repos/Codertocat/Hello-World/teams",
                "hooks_url": "https://api.github.com/repos/Codertocat/Hello-World/hooks",
                "issue_events_url": "https://api.github.com/repos/Codertocat/Hello-World/issues/events{/number}",
                "events_url": "https://api.github.com/repos/Codertocat/Hello-World/events",
                "assignees_url": "https://api.github.com/repos/Codertocat/Hello-World/assignees{/user}",
                "branches_url": "https://api.github.com/repos/Codertocat/Hello-World/branches{/branch}",
                "tags_url": "https://api.github.com/repos/Codertocat/Hello-World/tags",
                "blobs_url": "https://api.github.com/repos/Codertocat/Hello-World/git/blobs{/sha}",
                "git_tags_url": "https://api.github.com/repos/Codertocat/Hello-World/git/tags{/sha}",
                "git_refs_url": "https://api.github.com/repos/Codertocat/Hello-World/git/refs{/sha}",
                "trees_url": "https://api.github.com/repos/Codertocat/Hello-World/git/trees{/sha}",
                "statuses_url": "https://api.github.com/repos/Codertocat/Hello-World/statuses/{sha}",
                "languages_url": "https://api.github.com/repos/Codertocat/Hello-World/languages",
                "stargazers_url": "https://api.github.com/repos/Codertocat/Hello-World/stargazers",
                "contributors_url": "https://api.github.com/repos/Codertocat/Hello-World/contributors",
                "subscribers_url": "https://api.github.com/repos/Codertocat/Hello-World/subscribers",
                "subscription_url": "https://api.github.com/repos/Codertocat/Hello-World/subscription",
                "commits_url": "https://api.github.com/repos/Codertocat/Hello-World/commits{/sha}",
                "git_commits_url": "https://api.github.com/repos/Codertocat/Hello-World/git/commits{/sha}",
                "comments_url": "https://api.github.com/repos/Codertocat/Hello-World/comments{/number}",
                "issue_comment_url": "https://api.github.com/repos/Codertocat/Hello-World/issues/comments{/number}",
                "contents_url": "https://api.github.com/repos/Codertocat/Hello-World/contents/{+path}",
                "compare_url": "https://api.github.com/repos/Codertocat/Hello-World/compare/{base}...{head}",
                "merges_url": "https://api.github.com/repos/Codertocat/Hello-World/merges",
                "archive_url": "https://api.github.com/repos/Codertocat/Hello-World/{archive_format}{/ref}",
                "downloads_url": "https://api.github.com/repos/Codertocat/Hello-World/downloads",
                "issues_url": "https://api.github.com/repos/Codertocat/Hello-World/issues{/number}",
                "pulls_url": "https://api.github.com/repos/Codertocat/Hello-World/pulls{/number}",
                "milestones_url": "https://api.github.com/repos/Codertocat/Hello-World/milestones{/number}",
                "notifications_url": "https://api.github.com/repos/Codertocat/Hello-World/notifications{?since,all,participating}",
                "labels_url": "https://api.github.com/repos/Codertocat/Hello-World/labels{/name}",
                "releases_url": "https://api.github.com/repos/Codertocat/Hello-World/releases{/id}",
                "deployments_url": "https://api.github.com/repos/Codertocat/Hello-World/deployments",
                "created_at": "2019-05-15T15:19:25Z",
                "updated_at": "2019-05-15T15:19:27Z",
                "pushed_at": "2019-05-15T15:20:32Z",
                "git_url": "git://github.com/Codertocat/Hello-World.git",
                "ssh_url": "git@github.com:Codertocat/Hello-World.git",
                "clone_url": "https://github.com/Codertocat/Hello-World.git",
                "svn_url": "https://github.com/Codertocat/Hello-World",
                "homepage": None,
                "size": 0,
                "stargazers_count": 0,
                "watchers_count": 0,
                "language": None,
                "has_issues": True,
                "has_projects": True,
                "has_downloads": True,
                "has_wiki": True,
                "has_pages": True,
                "forks_count": 0,
                "mirror_url": None,
                "archived": False,
                "disabled": False,
                "open_issues_count": 2,
                "license": None,
                "forks": 0,
                "open_issues": 2,
                "watchers": 0,
                "default_branch": "master"
            },
            "sender": {
                "login": "Codertocat",
                "id": 21031067,
                "node_id": "MDQ6VXNlcjIxMDMxMDY3",
                "avatar_url": "https://avatars1.githubusercontent.com/u/21031067?v=4",
                "gravatar_id": "",
                "url": "https://api.github.com/users/Codertocat",
                "html_url": "https://github.com/Codertocat",
                "followers_url": "https://api.github.com/users/Codertocat/followers",
                "following_url": "https://api.github.com/users/Codertocat/following{/other_user}",
                "gists_url": "https://api.github.com/users/Codertocat/gists{/gist_id}",
                "starred_url": "https://api.github.com/users/Codertocat/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/Codertocat/subscriptions",
                "organizations_url": "https://api.github.com/users/Codertocat/orgs",
                "repos_url": "https://api.github.com/users/Codertocat/repos",
                "events_url": "https://api.github.com/users/Codertocat/events{/privacy}",
                "received_events_url": "https://api.github.com/users/Codertocat/received_events",
                "type": "User",
                "site_admin": False
            }
        }

        github_client=GithubClient()
        pull_request = GitHubPullRequestFactory(github_client).create_pull_request(pull_request_webhooh_payload)
        self.pull_request_repo.save_or_update_pull_request(pull_request)
        pull_request_db = self.pull_request_repo.get_pull_requests(pull_request.pull_request_id,
                                                                   pull_request.repository_url)


        #TODO Add more assertions and mock commit url call
        assert pull_request_db[0].action == 'closed'
        assert pull_request_db[0].branches[0].branch.name == 'changes'
        assert len(pull_request_db[0].branches) == 2
        assert len(pull_request_db[0].commits) == 1
        assert pull_request_db[0].commits[0].commit.sha_id == 'ec26c3e57ca3a959ca5aad62de7213c562f8c821'





if __name__ == '__main__':
    unittest.main()
