"""init tables

Revision ID: 2739bf44caf4
Revises: 
Create Date: 2020-01-30 20:57:38.194763

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '2739bf44caf4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('issues',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('issue_id', sa.VARCHAR(length=128), nullable=True),
    sa.Column('title', sa.VARCHAR(length=128), nullable=True),
    sa.Column('description', sa.VARCHAR(length=256), nullable=True),
    sa.Column('reported_by', sa.VARCHAR(length=128), nullable=True),
    sa.Column('sev', sa.VARCHAR(length=128), nullable=True),
    sa.Column('start_time', mysql.TIMESTAMP(), nullable=True),
    sa.Column('end_time', mysql.TIMESTAMP(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pull_request',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('repository_url', sa.VARCHAR(length=128), nullable=False),
    sa.Column('pull_request_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.VARCHAR(length=128), nullable=False),
    sa.Column('action', sa.VARCHAR(length=128), nullable=False),
    sa.Column('commits_urls', sa.VARCHAR(length=1024), nullable=False),
    sa.Column('merged_at', mysql.TIMESTAMP(), nullable=True),
    sa.Column('created_at', mysql.TIMESTAMP(), nullable=False),
    sa.Column('update_at', mysql.TIMESTAMP(), nullable=False),
    sa.Column('closed_at', mysql.TIMESTAMP(), nullable=True),
    sa.Column('merge_commit_sha', sa.VARCHAR(length=255), nullable=True),
    sa.Column('no_of_review_comments', sa.Integer(), nullable=True),
    sa.Column('no_of_comments', sa.Integer(), nullable=True),
    sa.Column('no_of_commits', sa.Integer(), nullable=True),
    sa.Column('no_of_files_changed', sa.Integer(), nullable=True),
    sa.Column('lines_added', sa.Integer(), nullable=True),
    sa.Column('lines_removed', sa.Integer(), nullable=True),
    sa.Column('sender_username', sa.VARCHAR(length=128), nullable=False),
    sa.Column('sender_user_id', sa.VARCHAR(length=128), nullable=False),
    sa.Column('row_created_at', mysql.TIMESTAMP(), nullable=True),
    sa.Column('row_updated_at', mysql.TIMESTAMP(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('repository_url', 'pull_request_id', name='repo_pull_request_id_unique_key')
    )
    op.create_table('pull_request_branch_association',
    sa.Column('pull_request_id', sa.Integer(), nullable=False),
    sa.Column('branch_id', sa.Integer(), nullable=False),
    sa.Column('branch_type', sa.VARCHAR(length=128), nullable=True),
    sa.ForeignKeyConstraint(['branch_id'], ['branch.id'], ),
    sa.ForeignKeyConstraint(['pull_request_id'], ['pull_request.id'], ),
    sa.PrimaryKeyConstraint('pull_request_id', 'branch_id')
    )
    op.create_table('pull_request_commit_association',
    sa.Column('pull_request_id', sa.Integer(), nullable=False),
    sa.Column('commit_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['commit_id'], ['commit.id'], ),
    sa.ForeignKeyConstraint(['pull_request_id'], ['pull_request.id'], ),
    sa.PrimaryKeyConstraint('pull_request_id', 'commit_id')
    )
    op.create_table('pull_request_participant',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.VARCHAR(length=128), nullable=True),
    sa.Column('display_name', sa.VARCHAR(length=128), nullable=True),
    sa.Column('role', sa.VARCHAR(length=128), nullable=True),
    sa.Column('participated_on', mysql.TIMESTAMP(), nullable=True),
    sa.Column('approved', sa.BOOLEAN(), nullable=True),
    sa.Column('pull_request_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['pull_request_id'], ['pull_request.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pull_request_participant')
    op.drop_table('pull_request_commit_association')
    op.drop_table('pull_request_branch_association')
    op.drop_table('pull_request')
    op.drop_table('issues')
    # ### end Alembic commands ###
